[package]
name = "simple-raytracer-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "srt" # Simple RayTracer
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
glam = "0.30.1"
image = "0.25.6"
